### ISSUE TITLE
Troubles with Docker Image 

### ISSUE THREAD

**Issue by EmSi14** [cisagov/.github#54]
# 🐛 Summary #

Hello, I've been trying to install decider via the docker method and have gotten past the 'db' and 'web' errors, but now I've gotten
to the docker 'compose' is not a docker command. I have v2.17.0 installed and can't seem to have any luck with finding a solution. Thanks.

**Comment by dav3r** [comment]
You will have more luck if you create this issue in the ['cisagov/decider' repo](https://github.com/cisagov/decider).  

FYI, in 2021 Docker modified the syntax so that the `docker-compose` command became `docker compose`, so you may want to verify that your Docker software is up-to-date.  See [here](https://docs.docker.com/compose/reference/) for more info.

I'm going to close this issue since it doesn't belong here, but please feel free to open another one in the ['cisagov/decider' repo](https://github.com/cisagov/decider/issues) if necessary.
